export const medicalProfessional = {
  fullName: "Dr. John Doe",
  initials: "DJD",
  profession: "Hospital Administrator",
};

export const dashboardCards = [
  { icon: "FaUser", label: "Patients", count: 150, bgColor: "bg-green-50" },
  {
    icon: "FaFileAlt",
    label: "Lab Reports",
    count: 50,
    bgColor: "bg-yellow-50",
  },
  { icon: "FaComments", label: "Urgent", count: 10, bgColor: "bg-blue-50" },
  { icon: "FaUserFriends", label: "Surgeries", count: 5, bgColor: "bg-red-50" },
];

export const patients = [
  {
    id: "P001",
    initials: "JD",
    name: "John Doe",
    checkInDate: "2024-10-10",
    disease: "Flu",
    appointmentType: "Regular Check-up",
    mode: "In-Person",
    date: "2024-10-10",
    time: "09:00 AM",
    town: "Springfield",
    insured: true,
    age: "30",
    sex: "Male",
    education: "Bachelor's Degree",
    occupation: "Engineer",
    religion: "Christianity",
    maritalStatus: "Married",
    assignedDoctor: {
      name: "Dr. Stella",
      image: "https://randomuser.me/api/portraits/men/3.jpg",
    },
  },
  {
    id: "P002",
    initials: "JD",
    name: "Jane Doe",
    checkInDate: "2024-10-10",
    disease: "Stomach Ache",
    appointmentType: "Regular Check-up",
    mode: "Online",
    date: "2024-10-10",
    time: "10:30 AM",
    town: "Riverdale",
    insured: false,
    age: "28",
    sex: "Female",
    education: "Master's Degree",
    occupation: "Teacher",
    religion: "Christianity",
    maritalStatus: "Single",
    assignedDoctor: {
      name: "Dr. Emma",
      image: "https://randomuser.me/api/portraits/women/4.jpg",
    },
  },
  {
    id: "P003",
    initials: "MK",
    name: "Michael King",
    checkInDate: "2024-10-11",
    disease: "Cold",
    appointmentType: "Regular Check-up",
    mode: "In-Person",
    date: "2024-10-11",
    time: "11:00 AM",
    town: "Hillside",
    insured: true,
    age: "40",
    sex: "Male",
    education: "High School",
    occupation: "Driver",
    religion: "Islam",
    maritalStatus: "Married",
    assignedDoctor: {
      name: "Dr. John",
      image: "https://randomuser.me/api/portraits/men/4.jpg",
    },
  },
  {
    id: "P004",
    initials: "AS",
    name: "Anna Smith",
    checkInDate: "2024-10-12",
    disease: "Headache",
    appointmentType: "Consultation",
    mode: "Online",
    date: "2024-10-12",
    time: "01:30 PM",
    town: "Seaside",
    insured: false,
    age: "25",
    sex: "Female",
    education: "Bachelor's Degree",
    occupation: "Designer",
    religion: "Hinduism",
    maritalStatus: "Single",
    assignedDoctor: {
      name: "Dr. Sara",
      image: "https://randomuser.me/api/portraits/women/5.jpg",
    },
  },
];
